### ISSUE TITLE
关于代码问题

### ISSUE THREAD

**Issue by GorgeousMe** [zhoushengisnoob/CKD#2]
我在用HAN代码跑PubMed的数据集时候，其结果只有Test loss 2.0676 | Test Micro f1 0.2442 | Test Macro f1 0.0983，与您的论文报的结果相差太大，您可以提供一下做对比实验时候HAN的代码吗？我想知道我哪里弄错了

**Comment by zhoushengisnoob** [comment]
如果是HAN的代码的话，我建议可以找HAN的Github源码？
https://github.com/Jhy1993/HAN
